### ISSUE TITLE
Don't break up anything in the log

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#1028]
`BEFORE` is a string. `AFTER` is a list. It is frustrating to parse the output changes in the log because everything is breaking up into new lines or new lists.... especially when you yourself are trying to break up the output into new lines or new lists too using line feed and/or separators in the new modules.

Right now, the string outputs looks just same as list outputs... minus the commas.
We could make a longer width or just let the terminal wrap everything.
```
Module `test_module`: 'BEFORE'
Module `test_module`: '-------------------
Module `test_module`:
('py3status0006\x1b\x1e'
 'Hi\\\\n\\\\n\\\\n\\012\x1b\x1e'
 '9\x1e'
 '\x1c'
 '\n'
 'py3status0004\x1b\x1e'
 '128     Run module in test mode.\\012\x1b\x1e'
 '33\x1e'
 '\x1c'
 '\n'
 'py3status0003\x1b\x1e'
 '1d [chris:~/src/py3status/py3status/modules] b63f26ec+* ±\\012\x1b\x1e'
 '59\x1e'
 '\x1c'
 '\n')
Module `test_module`: 'AFTER'
Module `test_module`: '-------------------
Module `test_module`:
['py3status0006\x1b\x1eHi\\\\n\\\\n\\\\n\\012\x1b\x1e9',
 '\x1f\x1bpy3status0004\x1b\x1e128     Run module in test mode.\\012\x1b\x1e33',
 '\x1f\x1bpy3status0003\x1b\x1e'
 '1d [chris:~/src/py3status/py3status/modules] b63f26ec+* ±\\012\x1b\x1e'
 '59',
 '\x1f\x1b']
```

**Comment by tobes** [comment]
@lasers 

I'm not sure what you are saying here.

Without knowing what you are logging and what you expect to see (minimal example) it is hard to know if there is an issue.

In logging we try to make the output as user friendly as possible so we format `dict`, `list`, `set`, and `tuple` nicely using `pprint` strings we log as we get them although we start multi-line ones on a new line so that the indentation matches for all lines.

> especially when you yourself are trying to break up the output into new lines or new lists too using line feed and/or separators in the new modules.

I think this is probably the issue.

**Comment by lasers** [comment]
```
py3status0006\x1e9\x1eHi\\n\\n\\n\012
py3status0004\x1e33\x1e128     Run module in test mode.\012
py3status0003\x1e59\x1e1d [chris:~/src/py3status/py3status/modules] b63f26ec+* ±\012
```
This is the context. I'd like to preserve `\n` and such. I'm using control separators between values because of that `\\n\\n\\n` and other output that could affect the splitting. I also can't use `splitlines()` since it seems to be stripping `\n` and control separators so I'm either filling or replacing them with more than 1 control separators... then start splitting things up.

**Comment by tobes** [comment]
ok makes more sense does #1034 do what you want

**Comment by tobes** [comment]
@lasers 

when you edit your comments that fundementally change them it makes me sad because I have no idea you have done this.  Edit comments to fix grammer/spelling/formatting etc but not for big changes just add a new comment.

If the old one is so bad then just delete it but that way the issue remains readable and things do not get lost

```
        string = 'what\nis\nthis!'
        self.py3.log(string)    # nice and readable
        self.py3.log('%r' % string)  # keep \n visible
```

your example is still terrible

better would be:

```
self.py3.log('this\nis\na\ntest')
```

saw
```
'this\nis\na\ntest'
```

expected
```
this
is
a
test
```

**Comment by lasers** [comment]
I can't test it without https://github.com/ultrabug/py3status/pull/1033. I have been working on a new module using `post 3.6` commit. It's not a problem to live without the `list` although you can see that it splits the list too. Many thanks for this fix!
