### ISSUE TITLE
New module - external_script

### ISSUE THREAD

**Issue by frimdo** [ultrabug/py3status#104]
I have written a new module. Do you want to add it to yours?
https://gist.github.com/frimdo/804b7d8737a0fe2ffcaa

**Comment by ultrabug** [comment]
Hi @frimdo 

Thanks for this proposal, I think that this kind of module is indeed a good idea !

Maybe you could call this script `external_script` ? I have a few remarks wrt your code :
* 1 second cache_timeout is a bit short and would hammer machines, maybe a default of 15 would be better
* output_color could be called `color`, sounds simpler
* make sure it runs with both python2 and python3 please and that it is PEP8 compliant
* defaulting to `whoami` script sounds weird since there already is a `whoami` module available :) maybe provide no default and handle this properly on the code ?

**Comment by frimdo** [comment]
OK, [here](https://gist.github.com/frimdo/45b8a2dbb260366bc9ef) is `<external_script>`, everything should work and be ready to go ;-)

**Comment by ultrabug** [comment]
this module was added in your PR, closing
