### ISSUE TITLE
Py3status Battery_level notifications formatted incorrectly

### ISSUE THREAD

**Issue by Cypher1** [ultrabug/py3status#1079]
I'm having an issue where the string sent by the battery_level module (to my notifications daemon) has been mangled.
When I click to get a notification containing something like:
```
<Composite [{'full_text': '00:53 till fully charged. (47*)'}]>
```
Rather than just
```
00:53 till fully charged. (47*)
```

I'm running: **py3status version 3.6** and **python 3.5.2**

Here is the relevant section of my i3status.conf:
```
battery_level {
  format_notify_charging = "{time_remaining} till fully charged. ({percent}%)"
  format_notify_discharging = "{time_remaining} remaining ({percent}%)"
  notification = True
  notify_low_level = True
}
```

**Comment by lasers** [comment]
Confirmed. @tobes I think cb63abf8c broke this because `notify_user` is getting a composite instead of a `string`. Do we have something to simplify a composite into a string? Should `notify_user` even check for a composite and break it down into a string... or I think we can just do that ourselves.

Also, if not possible, do we rename `format_notify_charging` and `format_notify_discharging` since there might be no gain in safeformatting the values? Other than length and such...

@Cypher1 This module definitely could be updated... New thresholds, remove hardcoded strings, simplifications, and whatnot.

**Comment by Cypher1** [comment]
I'm all for safer formatting etc. I do have a concern that the formatting rules are not well known and that they make the configs harder to read but the flexibility that they offer is nice.
I've changed this in my fork to just use format.format(<kwargs>) rather than safe format.
It's not as nice in practice but it works for my everyday usage.

**Comment by tobes** [comment]
@Cypher1 thanks for reporting this.  I've made a PR #1081 to fix the issue.

**Comment by Cypher1** [comment]
Thanks @tobes 

Closed in #1081

**Comment by lasers** [comment]
@tobes I think if we want to deprecate the thresholds in this module, we might need something like `self.py3.threshold_get_name` or a new parameter for `self.py3.threshold_get_color` where it can return `bad`, `degraded` or `full` after we give it a number to determine.

Current
```
     threshold_bad: a percentage below which the battery level should be
         considered bad
         (default 10)
     threshold_degraded: a percentage below which the battery level should be
         considered degraded
         (default 30)
     threshold_full: a percentage at or above which the battery level should
         should be considered full
         (default 100)
```
Ideal
```
thresholds = [(10, 'bad'), (30, 'degraded'), (100, 'good')]
```
Parse `battery_level.py: def _set_bar_color(self)` and tell me what you think. The changes would look something like this...
```
        name = self.py3.threshold_get_color(percent, name=True)
        if ...
        ...
        ... 
        elif name == 'bad'
            message = 'Battery level is critically low ({}%)'
            level = 'error'
        elif name == 'degraded'
            message = 'Battery level is running low ({}%)'
            level = 'warning'
         ...
```
I don't know if it's ideal because if users do `thresholds = []` then notification would stop working, but in this scenario, it makes sense since there are now no thresholds to work with. Also, it could suck deprecating things like `hide_when_full` when we merge `formatter: allow condition` and more new conditions in the near future.&nbsp;&nbsp;&nbsp;&nbsp;(.__.)

**Comment by tobes** [comment]
> I think if we want to deprecate the thresholds in this module

@lasers really this is a separate issue.  Anyhow yes we should use proper thresholds but then it breaks the notifications.  So we likely want to have different settings for each.  It would be good to do a clean of several modules, maybe this is something for 3.8

**Comment by Cypher1** [comment]
If I have time over the next few weeks I'd love to learn about the new
module API and design. Is there a fully updated module I could use to start
work on a PR for updating or replacing some of the older modules?

**Comment by lasers** [comment]
[ReadTheDocs](https://py3status.readthedocs.io/en/3.6) // Alt [Github](https://github.com/ultrabug/py3status/tree/master/doc)

>Is there a fully updated module I could use to start work on a PR for updating or replacing some of the older modules?

I'd say to start looking at `coin_market` because it is the newest module, then `moc` and `cmus`. I don't know if they all are good modules to start working off on... We also have to have a conversation about formatting, keeping things simple, making things too complicated, etc.

You could try this first as I don't mind doing this someday... Make `apt_updates` more nice like `void_updates` https://github.com/ultrabug/py3status/pull/1014 or `arch_updates` https://github.com/ultrabug/py3status/pull/1075. Expose `name`, `old_version`, `new_version`, `(any possible separate counts?)`, etc... placeholders for the users. Play with the command and/or its parameters first... See if you can expose more. Look at other commands too.

**Comment by Cypher1** [comment]
Okay. Sounds like a plan. Thanks (I didn't know there was real
documentation. Great news).

**Comment by tobes** [comment]
>  Is there a fully updated module I could use to start work on a PR for updating or replacing some of the older modules?

I'd say there is currently no fully updated module to use as a best practice guide.  This is for several reasons but mainly the way that 'best practice' evolves and so modules are moving towards a better state but still retain some quirks because of their history.  The modules @lasers has mentioned I feel are over complex and as such not great examples and they have technical debt already.  The best example module is [static_string](https://github.com/ultrabug/py3status/blob/master/py3status/modules/static_string.py) due to its innate purity but it could still be improved.

As far as replacing/updating modules goes.  This is only of value if it adds benefit, ie fixes some bug or other issue, otherwise it is code churn which just uses up project resources.  The best way to contribute is to start with small fixes for real problems.  There is also lots of help around documentation etc which could always be improved.
