### ISSUE TITLE
window_title module

### ISSUE THREAD

**Issue by tribeiros** [ultrabug/py3status#1184]
could have more options in `format={title}` , to remove some attributes ?
example: remove 'google chrome' from the title of chrome app, viewing only site name.

**Comment by lasers** [comment]
You can try this for now. [window_title_changes+scrub/window_title.py](https://github.com/lasers/py3status/blob/window_title-changes+scrub/py3status/modules/window_title.py)

**Comment by tribeiros** [comment]
Thanks, worked with Google Chrome, but for some reason does not work with Sublime text.

window_title {
    format = '{title}'
    scrub = {
        'title': [
            ' - Sublime Text (UNREGISTERED)$',
            ' - Google Chrome$',
        ]
    }

i miss something ?

**Comment by lasers** [comment]
You have some choices.
* `' - Sublime Text \(UNREGISTERED\)$',`  # escape the parentheses
* `' - Sublime Text.*$',` # match this wildcard and everything after it
* `' - .*$'` # match this wildcard and everything after it.

**Comment by tribeiros** [comment]
Worked, regex !!!
Thanks

**Comment by tribeiros** [comment]
i was thinking .... 
it's possible window_title show a specific title app of a inactive workspace ?

**Comment by lasers** [comment]
Not possible for this module because it would be out of scope for this module's purpose. You could try this https://github.com/ultrabug/py3status/pull/985. I stopped working on it due to i3wm bugs that I kept tripping repeatedly.

This does not guarantee the feature, but I think it may give you more than what you're looking for... and thinking back on the code, this feature could be implemented in `window_manipulations` easily via `[\?is_workspace_inactive]` thing.
