### ISSUE TITLE
support shorthand hexadecimal

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#1200]
Right now, the config support six-digit hexadecimal.
```python
# working - success
module {
    color_good = '#00FF00'
    color_bad = '#FF0000'
    color_degraded = '#FFFF00'
    color_charging = '#00FFFF'
}
```
Request feature: The config is to support shorthand three-digit hexadecimal too.
```python
# not working - failure
module {
    color_good = '#0F0'
    color_bad = '#F00'
    color_degraded = '#FF0'
    color_charging = '#0FF'
}
```
Optional: The config is to support x11 color names too.
```python
# not working - future rgb names
module {
    color_good = 'steelblue`
    color_bad = 'rosered'
    color_degraded = 'cornyellow`
    color_charging = 'tobespink`
}
```
Too much! The config is to support rgb numbers too.
```python
# not working - future rgb numbers
module {
    color_good = rgb(0, 255, 0)
    color_bad = rgb(255, 0, 0)
    color_degraded = rgb(255, 255, 0)
    color_charging = rgb(255, 0, 255)
}
```

**Comment by tobes** [comment]
> `color_charging = '#0FF'`

This should be implemented we should support `#FF00FF` and `#F0F` universally

> `color_good = rgb(0, 255, 0)`

I'd be happy for us to support this in the config if it is implemented

> `color_charging = 'tobespink'`

This I don't mind too much either `color_charging = tobespink` would also work because we allow unquoted strings, I'd be inclined to use css3 colors rather than x11.  It might be a little confusing to user though.  Unfortunately `tobespink` is still not through the committee stages.

**Comment by lasers** [comment]
Filing a possible issue... Composite might not parse shorthand hexadecimal too.
