### ISSUE TITLE
Q: implement new modules or use external_script?

### ISSUE THREAD

**Issue by maximbaz** [ultrabug/py3status#1217]
I noticed that some modules follow exactly the same pattern: execute a command and shows its output, potentially also manipulating the format and colors based on the output text. 

Just a few examples, there are potentially more:
- dropboxd_status: `dropbox-cli`
- scratchpad_counter: `i3-msg -t get_tree | jq '.floating_nodes | length'`
- yandexdisk_status: `yandex-disk status`
- process_status: `pgrep NAME >/dev/null 2>&1 && echo ON || echo OFF`
- online_status: `ping -c 1 google.com >/dev/null 2>&1 && echo ON || echo OFF`

I'm not sure if I know all the magic of `format`, but I have a feeling that all of these could be very simply achieved with just `external_script` module. Recently I actually needed a couple of new modules of similar kind, and instead of submitting PRs I just implemented them via `external_script`. 

My question thus is the following: what is the desired way from the project's standpoint, should all of these simple modules be implemented as new separate modules, or should `external_script` and the magic of `format` be promoted? Is there any kind of "complexity" bar for the new modules? 

I imagine there is a burden of maintaining hundreds of modules that are very simple in their implementation, but at the same time it's more pleasant to just include `dropboxd_status` in the `.i3status.conf` rather than think how to do so via `external_command`.

P.S. as an exercise I'm curious if it is possible to use `format` to fully reimplement `dropboxd_status` with `external_script`. The tricky parts are replacing some text to something else (`Dropbox isn't running` -> `isn't running`) while keeping the other output untouched, and using different color based on the output string (`isn't running` -> red color). Is it possible to achieve?

**Comment by lasers** [comment]
* `whoami.py` - $ whoami
* `uname.py` - $ uname
* `whatismyip.py` - $ curl some-nice-ip-website
* `systemd.py` - $ script.{py,sh,pl,etc} + systemctl status sshd (w/ sudo privilege)
* `et_cetera.py` - $ script{py,sh,pl,etc} + your_goal_here
* `xrandr_rotate.py` - `switch.py` w/ reasonable commands. :-)

>what is the desired way from the project's standpoint

Any modules will do if the users finds them useful... I think is the goal.

>should all of these simple modules be implemented as new separate modules, or should external_script and the magic of format be promoted? Is there any kind of "complexity" bar for the new modules?

We're catering to everybody including average users that might not know how to read or write scripts... so they could just use modules instead... and also, technically we could have just one `external_script` module with bunch of scripts... but is much nicer for everybody to see what modules they can use... instead of having to figure out scripts themselves.

What simple modules are we talking about? I think by making modules, we can share this with others... If we make scripts, we might keep it ourselves and not sharing... because it's not perfect or is too simple.... I dunno.

>Is there any kind of "complexity" bar for the new modules?

I think the problem is translating from old formats to new formats...  Might be too hard to deprecate... and that users wouldn't understand this new stuffs... And still no documentation too... If we put out new modules with new formats, then there would be almost nothing to fix if we make all placeholders (including control placeholders) available right away for users to tweak with.

I'm a fan of including examples so users can kinda see how it works... and so they can copy and paste the configs in without doing any (or very little) adjustment.

>P.S. as an exercise I'm curious if it is possible to use format to fully reimplement dropboxd_status with external_script. The tricky parts are replacing some text to something else (Dropbox isn't running -> isn't running) while keeping the other output untouched, and using different color based on the output string (isn't running -> red color). Is it possible to achieve?

I made this last week, but shouldn't put out any new pull requests... Lol. https://github.com/lasers/py3status/commit/df1a8e6bed014e5ca1ed0494093805cf6f03c5d5 

I think  `[\?if=status~running&color=bad Dropbox isn't running]` would solve this issue.
```
# my guess of how dropbox new format could look like... untested....
format =  '[\?if=status~running&color=bad Dropbox isn't running'
format += '|[\?if=status~Date&color=good Up to date]'
format += '|[\?color=degraded {status}]]'
```
Easier alternative: Use `format = {status}` instead (w/o colors.. or static light blue color).

**Comment by tobes** [comment]
I think this is a great question, and deserves a good answer.

I'll try and put down my thoughts when I'm back home and see can see what @ultrabug has to say too.

**Comment by lasers** [comment]
I played a little. Using `external_script` with lasers/py3status@df1a8e6 works okay.
```
external_script {
    script_path = 'dropbox status'
    format = "[\?if=output~running!&color=bad Dropbox isn't running!"
    format += "|[\?if=output~Up&color=good Up to date"
    format += "|\?color=degraded&show {output}]]"
}
```
```
{'full_text': "Dropbox isn't running!", 'color': '#FF0000', 'cached_until': 1515476683.0}
{'full_text': 'Connecting...', 'color': '#FFFF00', 'cached_until': 1515476629.0}
{'full_text': 'Waiting to be linked to a Dropbox account...', 'color': '#FFFF00', 'cached_until': 1515476640.0}
{'full_text': 'Starting...', 'color': '#FFFF00', 'cached_until': 1515476646.0}
{'full_text': 'Up to date', 'color': '#00FF00', 'cached_until': 1515476712.0}
```
Minor issues of syncing files with `running!` and `Up` name:
* `Dropbox isn't running!` instead of `Indexing "a_running!_game.zip"`
* `Up to date` instead of `Syncing "Update_Manager.txt"`

Suggestion: Add more formatters such `[\?if=output$running!` and `[\?if=output^Up]` too, but `Up` can have  a conflict with `Uploading` too. I wonder if we can support spaces and/or quotes? Here's a list of `{status}` output I was able to harvest.
```
    -------- Connecting...
    -------- Downloading file list...
    -------- Dropbox isn't responding!
    -------- Dropbox isn't running!
    -------- Indexing "filename"...
    -------- Starting...
    -------- Syncing "filename"
    -------- Syncing (3 files remaining)
    -------- Up to date
    -------- Uploading "filename"...
    -------- Uploading 3 files...
```

**Comment by tobes** [comment]
Personally, I think it is important to have some modules that do specific things eg `dpms` this could be done by using external script or similar, but it is nice to have the module so that users can easily access the functionality.  It is nice to have lots of modules as this shows what we can do.

We do have lots of things that we could implement without needing a module.  I often use the `static_string` module - for example to lock my screen/suspend.  This feels like making a module would be silly.  I think maybe we should create a `recipes` type section in the documentation for these type things so that users can copy/adapt them, rather than adding new  modules.

If we find that there are limitations we can always look at improving things.  eg my suspend module calls a script to lock screen then suspend, and I can't remember exactly why I couldn't put all the logic straight into the onclick of the module.

So I'd say to answer your question "should all of these simple modules be implemented as new separate modules?"  It depends.  Generally I'd say using external script/static_string if it can all be done in the i3status.conf is the way to go.  If we need to actually call a script rather than just calling a command etc then maybe a module is better.  I think modules for key feature are ok too,  but yes maintaining all the modules takes time and energy.

**Comment by maximbaz** [comment]
Thanks for the answers
