### ISSUE TITLE
release 3.8 needs changelog

### ISSUE THREAD

**Issue by ultrabug** [ultrabug/py3status#1320]
The CHANGELOG needs time and work so we can release 3.8

From this issue on, I will not merge anything else than contributions to the 3.8 CHANGELOG and critical bug fixes to ensure that we get a 3.8 as soon as possible!

**Comment by lasers** [comment]
`deadbeef`

Put out two PRs to address https://github.com/ultrabug/py3status/issues/1293?
1) Deprecate `7.0, 7.1`. More than 1 year and 8 months since the last release so I think everybody are mostly on `7.2`. This just removes a bad `if` statement.
2) Remove subprocess stuffs in favor of a helper. Tested okay by me and OP.
3) Extra. New toggleable buttons. 

`pomodoro:` 
Merge new `pomodoro` from scratch?

1) Turn multiple new `format` into a single `format` along with many changes?
2) I hadn't performed last minute improvements so I'd like to go through that again tbh.
3) Avoid complications such as non `safe_format` and whatnot, but new PR mean new complication, I guess.

That's all I can think of right now. I need to look thru issues/prs again... to expand the list.

**Comment by lasers** [comment]
@ultrabug If you want to merge more issues... You can merge them all except 10.

1. TRAVIS: `1321: fix travis whitespace error`
    * HARD MERGE. Ugh.

2. BUGFIX: `1312: py3: play sounds with ffplay`
    * Satisfied? Merge.

3. BUGFIX: `1307: pomodoro: fix off-by-one error overworking the user`
    * HARD MERGE. Easy bugfix.

4. BUGFIX?:`1313: pomodoro: new module from scratch`
    * Satisfied? Merge? LGTM. Many new features.

5. SIMPLIFYING `1305: sysdata: rename cpu_usage to cpu_used_percent`
    * Merge? To continue simplifying `sysdata`. This stalled.

6. ENHANCEMENT `1300: deadbeef: add dead man's switches`
    * Merge. LGTM. New usable buttons.

7. BUGFIX: xxxx: I make a `deadbeef` PR to deprecate old versions support?
8. IMPROV: xxxx: I make a `deadbeef` PR to use py3 helper instead?

9. MODULE `1134: add new module: nvidia_smi`
    * HARD MERGE. LGTM. 1 year anniversity this week.

10. MODULE `1226: add new module: xrandr_lamo`
    * Ready. LGTM. Do not merge now. LGTM. Merge now? 
    * Keep `lmao` or rename to something else? `xrandr_plus`? Idk. lmao.

Don't merge anything not on this list. Ty.

**Comment by ultrabug** [comment]
@lasers I think you misunderstood what I meant here. I need help on writing the CHANGELOG not in finding out which PRs to merge (and worsen the CHANGELOG) ;)

**Comment by lasers** [comment]
I got it down to 286 lines so far... I'll keep omitting stuffs.

**Comment by maximbaz** [comment]
awww, `3.8` will not include #1077? 😢 

But I understand the intention to finalize the release of existing merges 😉

**Comment by ultrabug** [comment]
Thanks a lot guys!
