### ISSUE TITLE
[idea] on battery / ac detection, idle detection, network online helpers? rfc

### ISSUE THREAD

**Issue by cyrinux** [ultrabug/py3status#1365]
I was thinking if it could be possible to for example change the default cache_timeout / refresh time according the the power state. This for power consumation for example.
When you love py3status, this one can be heavy, would be cool to be have auto builtin switch system, without do shell/wm hack. 
* Should this be an helper for modules ? As an helper which return AC state?
* Other idea is the possibility to have for example one "group" activate according to the battery (can be extended for other criterea later)
This was my evening thinking about this cool project.
* Other idea is to have an global option for enable an idle detector. If idle, calm down all module, think there is a X11 idle module. (with delay, for example if i don't move cursor while playing movie, youtube in fullscreen, not usefull to refresh module, not totally true but this is for the idea)

In the same way, helpers for "online" / "not online" can be usefull and prevent sooner  exec of some modules if user set for example  someting like this:

```
online = group online
offline = group offline

group online {
   module module1 {}
   module module2 {}
}

group offline {
   module module3 {}
   module module4 {}
}
```

What do you think about?

**Comment by maximbaz** [comment]
Idle detection is interesting, when I lock my screen and go for lunch, I don't need py3status to refresh modules. However, when I'm watching a movie in full screen, I tend to keep py3status visible and I do want refresh to happen — e.g. I monitor time and battery level.

Having different `cache_timeout` for when on battery vs AC sounds interesting, but I think it makes sense for someone to validate this idea first. Collect real data, increase timeouts manually in the config and try to observe how much longer your battery survives. I'm concerned that this could be a complex feature with little benefit, but I'm happy to be proven otherwise 🙂

**Comment by cyrinux** [comment]
Thanks @maximbaz, @lasers @ultrabug what do you think?

**Comment by lasers** [comment]
Don't forget @tobes.

**Comment by cyrinux** [comment]
Don't know yet all the familly sorry ;)

**Comment by lasers** [comment]
Simplifying this down to...
```python
on_ac {           | on_internet {
    module_one {} |     coin_market {}
    module_two {} |     github {}
}                 | }
```
Do you have any real modules for `on_ac` examples that you would like to avoid?

First, I wonder if `py3status --interval` is a dead config.
Second, I wonder if it would be better if `py3status` could reload config when users do `killall -SIGUSR1 py3status`. Otherwise, we have to `i3 restart` to get new changes.

With this in place, then users could do much more than changing `cache_timeout`. Users could also enable/disable/change modules. Change colors, formats, and more.

Maybe if we move `--interval` to config instead...
```python
py3status {
    # rename interval to cache_timeout

    # replace cache_timeout in all modules if set
    # (and is less than the given cache_timeout)
    cache_timeout = 30

    # replace cache_timeout in all modules if set and on_battery
    # (and is less than the given cache_timeout_on_battery)
    cache_timeout_on_battery = 60
}
```

**Comment by lasers** [comment]
@cyrinux How can we detect if we're on battery?  No laptop here.

**Comment by cyrinux** [comment]
Good shortcut. Can test this. For example I would like to enable my wwan, vpn, wlan, only when not on ac, so when out my office. Only show coin market, software update check, several clock TZ when on AC at office.

**Comment by cyrinux** [comment]
For check we can read acpi or /sys path. Think we can take part on battery_level module.

**Comment by cyrinux** [comment]
Test on poor-mans-battery do main of the job for cache_timeout concern :) 

FYI, only imap IDLE module speak more than others, good first step.

* Next so we need helper for detect AC/battery and have a trigger.
 If we really want to have py3status main process be idle - so not have py3status check every second if we are on AC -  we can, as you say reload py3status , with simple udev AC rules.
But at reload should have helper for detect on battery/AC. 

* About module selection with `on_ac`, `on_internet`:
I can need:
- Always running module
- On AC
- On battery
- On internet
- On offline

* Must we think now to have embedded `on_*` flags?

**Comment by lasers** [comment]
This could need some thinking first because some modules already uses `sleep_timeout` for music players... so it can refresh few times (3) per minute instead of 12... so this technically is an in-module alias for `cache_timeout_on_sleep`.

Maybe we will come up with universal `cache_time` system , but we should have a family discussion first. Also, who know? Maybe we can toggle modules via commandline in the future too... eg `py3status modules disable dpms` which could then could triggered via `udev` based on power changes rather than checking every seconds.

I wonder if we want a `timeout` prefix just like `format_*`, eg `timeout_request`, `timeout_cache`, `timeout_sleep` (audio players), `timeout_battery`, `timeout_internet`, etc. If not, I guess okay. :-)

I think `--interval` should be in config because users should be able to specify it in `py3staus {}`, then down to individual module configs. I should check if `allow_urgent` even works in `py3status {}`. If not, then I think any config added in `py3status {}` should be in individual module configs too to simplify things more.

We don't have to require `on_*`. Is for consistency.

Maybe `pgrep` too, eg `pgrep_timeout = (60, 'moc')` as a replacement for `sleep_timeout`, or `sleep_timeout` if we specify `PGREP='pgrep -x moc'` in the code. I really dunno. Wait 4 fam.

**Comment by cyrinux** [comment]
Ok @lasers, l see, wait for others advises so.

**Comment by maximbaz** [comment]
Just sharing my use-case, I would very much appreciate if I could pause certain modules from updating while I'm offline. In particular, I have a few `external_script` modules that check available updates, and when I have no internet they fail. Usually when I reboot, py3status modules get executed before the laptop has the chance to connect to wifi, so I have a bunch of red modules that I need to refresh with middle click.

**Comment by ultrabug** [comment]
I have a branch with something that is close to this very topic for the py3status core.

When 3.13 is out, 3.14 should be a core oriented release imo (let's discuss this in #1526)

Maybe it will require some dependencies at some point but I think the core can indeed react better to the state of the machine, be it power, udev, or connectivity related!

**Comment by tobes** [comment]
> Maybe it will require some dependencies at some point

we can probably make them optional :) because they are about added functionality eg if we don't have udev we can still update every x seconds with minimal complexity imho

**Comment by ultrabug** [comment]
> we can probably make them optional :)

This is exactly what I'm doing on my branch
