### ISSUE TITLE
battery_level 'format' doesn't work

### ISSUE THREAD

**Issue by narspeth** [ultrabug/py3status#139]
or i just can't understand how it works. ```mode``` works fine.

**Comment by ultrabug** [comment]
Hi @narspeth 

Well this module has had quite some attention lately mainly thanks to @maximbaz.

The `mode` config is deprecated, you should use the `format` option and play with the available placeholders there. They are listed in the doc which you can get by running `py3status modules details`.

````
        {ascii_bar} - a string of ascii characters representing the battery level,
                      an alternative visualization to '{icon}' option
        {icon} - a character representing the battery level,
                 as defined by the 'blocks' and 'charging_character' parameters
        {percent} - the remaining battery percentage (previously '{}')

**Comment by ccryx** [comment]
I can confirm that using the format option doesn't work.
Relevant part of the config file:
```
order += "battery_level"
battery_level {
        format = "asdasd {percent}"
}
```
What I would expect: The text "asdasd x%" (with a value for x) is displayed.
What happens: A white block (I assume the default) is displayed.

I think this is not restricted to the battery widget. I observe a similar behavior with the pomodoro widget (keeps displaying the default format instead of my custom format).

**Comment by maximbaz** [comment]
@ccryx, perhaps a silly question to ask, but which version of `py3status` are you running? The latest `master`? 

I've just updated my py3status to the latest `master`, and with your config I observe "asdasd 39". Perhaps someone else could try as well and post their results? @ultrabug? :smile:

**Comment by ccryx** [comment]
I guess I should have just gone to bed last night :D It works fine with the latest git `master`.

**Comment by ultrabug** [comment]
@narspeth can we close this ? is it okay for you now ?

**Comment by ultrabug** [comment]
closing, reopen if needed mate.
