### ISSUE TITLE
Check local mailbox

### ISSUE THREAD

**Issue by mkaito** [ultrabug/py3status#143]
Can the imap module check a local Maildir?

**Comment by Horgix** [comment]
AFAIK, there isn't such a module available publicly for py3status.

However, if you are running Thunderbird on your computer and want to check the unread emails among those stored locally, you can use this (did it a some months ago before noticing there was already an imap module) :

Add the "unread-count" module to Thunderbird : https://addons.mozilla.org/en-US/thunderbird/addon/unread-count/ . It will essentially keep a file with the unread count updated inside, and you can use the following py3status module to find & parse it :

```python
    def getUnreadCount(self, i3s_output_list, i3s_config):
        user = pwd.getpwuid(os.geteuid())[0]
        tbFilePath = "/home/" + user + "/.thunderbird/"
        tbConfig = configparser.ConfigParser()
        profile = "default"
        tbConfig.read(tbFilePath + "profiles.ini")
        profiles = {}
        for section in tbConfig.sections():
            if 'name' in tbConfig[section] and 'path' in tbConfig[section]:
                profiles[tbConfig[section]['name']] = tbConfig[section]['path']
        unreadfile = tbFilePath + profiles[profile] + "/unread-counts"
        with open(unreadfile) as f:
            content = f.readlines()
        unreadCount = 0
        for line in content:
            unreadCount += int(line.split(':')[0])
        response = {
            'cached_until': time() + self.cache_timeout,
            'full_text': str(unreadCount)
        }
        return response
```

You'll find the entire module attached (.txt instead of .py because of Github extension checking). It doesn't contains much more than the previous function since it was made the quick & dirty way !

Hope it helps, if you have any questions feel free to ask :)

[unread_emails_thunderbird.txt](https://github.com/ultrabug/py3status/files/49914/unread_emails_thunderbird.txt)

**Comment by mkaito** [comment]
Nope, I use offlineimap, notmuch and emacs :stuck_out_tongue:

**Comment by ultrabug** [comment]
@mkaito are you sure $MAILDIR is a standard way to get a user's local mail directory ? On my machine this outputs nothing.

If you're willing to help and contribute this module, I'll be glad to provide guidance / review or even implement it for you, your call mate !

@Horgix : maybe we can also hook in your code above in the module and provide a `thunderbird = True` configuration to get it from the local thunderbird ? ;)

**Comment by mkaito** [comment]
@ultrabug nope, that was just an example. The default is usually `~/Maildir`.

I don't see why this needs to be a separate module. This and IMAP should be part of a `mail` module, in my opinion.

The `imap` module also won't work for me since I use a self signed SSL cert, and there doesn't seem to be an option to disable cert verification.

It's been a couple years since I wrote any python. I'm not sure I'm up for it :stuck_out_tongue:

**Comment by ultrabug** [comment]
@mkaito ok I get your points. I'll leave this issue open while I actually find the time to make an attempt at this.

**Comment by mkaito** [comment]
Thanks!

**Comment by pydsigner** [comment]
@mkaito What specific SSL error was imap giving you? There should be ways to make imap do what you need it to for auth.

It would be good to support maildir and mailbox formats though.

**Comment by pydsigner** [comment]
@mkaito Did you try the imap module before giving up on it? imap uses imaplib.IMAP4_SSL, which does not verify server certs itself....

**Comment by lasers** [comment]
@mkaito I put out https://github.com/ultrabug/py3status/pull/1210. Can you test this if you're still using local `Maildir`? Thanks! :-)

**Comment by lasers** [comment]
Closed via https://github.com/ultrabug/py3status/pull/1210.
