### ISSUE TITLE
Keyboard layout cache control

### ISSUE THREAD

**Issue by squizduos** [ultrabug/py3status#151]
Keyboard_control have cache_timeout = 10, hardcoded in source code. It leads to 10-second delay, while I change keyboard layout, for example, I change it from *us* to *ru*, for next 10 seconds i write russian symbols, but see *us* in keyboard layout indicator.

**Comment by Anon1234** [comment]
You can modify the `cache_timeout` parameter in your `i3status.conf` like this:
```
...
keyboard_layout {
        cache_timeout = 0
}
...
```

**Comment by ultrabug** [comment]
Just as @Anon1234 says ! :)

Also @squizduos I'd suggest NOT making a such low cache_timeout but instead **change your i3 binding** so that changing your layout also trigger a `killall -USR1 py3status` which will force reload your modules at once. You'll get the benefit of instant update without running a command every second in the background to check for the keyboard layout ;)

**Comment by ultrabug** [comment]
closing, please reopen if you need more help mate.
