### ISSUE TITLE
new to python a bit confused with setup

### ISSUE THREAD

**Issue by nkv123** [ultrabug/py3status#154]
I am new to python and to i3wm enviroment
I am sending screenshot of my bar and i3status.conf and piped vnstat command

I hope u can explain to me what I did wrong with vnstat
vnstat is installed it on my sistem (ubutnu 14.04)
as its seen in image "vnstat down","vnstat up","vnstat total"

![2015-12-24-00 46 50_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4409902/11987026/18d554a4-a9d8-11e5-99b0-0be726ed0f52.png)
[i3status.conf.txt](https://github.com/ultrabug/py3status/files/71325/i3status.conf.txt)
[vnstat.txt](https://github.com/ultrabug/py3status/files/71328/vnstat.txt)

**Comment by ultrabug** [comment]
Hello @nkv123 welcome then !

Ok here it is:
* you can remove the `(0 - 800: white, 800-900: yellow, >900 - red)` which is meant as a comment for the coloring variable.
* you can remove the `name` parameter because you already use an instance name `vnstat down`
* you should use the `format` parameter to say what you want to display for each instance, by default it's the `{total}` that's displayed which is why you have 3 times the same output

For example, for the `down` instance you would get:
````
    vnstat down {
        format = "down: {down}"
        coloring = {
            800: "#dddd00",
            900: "#dd0000",
         }
    }
````

The `format` parameter is cool because you have total freedom about what you display. To see the available placeholders (`{variables}`) see the doc by issuing `py3status modules details` !

Hope this helps :)

**Comment by nkv123** [comment]
Everything works now thx a lot
