### ISSUE TITLE
min_width in characters instead of pixels

### ISSUE THREAD

**Issue by docwalter** [ultrabug/py3status#1540]
I use i3bar with a variable width font and use py3status with `min_width` to keep the modules at fixed positions, even if a number and thus the text length changes. Until 3.12 `min_width` worked as in i3status, i.e. it contained a number of pixels (?) that were handed over to i3bar.

After upgrading to 3.13 I first thought my config was broken because several modules were missing. Then I realized that the new formatting logic expects `min_width` to be a number of characters. That can be confusing. I suggest to revert the behavior to the non-breaking old logic and add another option, e.g. `min_width_chars`, to support the new formatting logic.

**Comment by lasers** [comment]
@docwalter I put out #1551 renaming `min_width` to `min_length`. Can you test/confirm?

The config `align` is useless on py3status because unlike i3status, we can use more colors.

Not seeing that it is for pixel, it takes away a nice feature... so now we have it back. We also rename `align` to `position` to still allow users to align their modules with `min_width`... only that it will work better if the output is painted fully with a single color. If you want more colors, then you have to use `min_length` and `position` ... but no min_width (pixel).

**Comment by ultrabug** [comment]
Thanks for reporting @docwalter and for fixing @lasers
