### ISSUE TITLE
mpd_status: Module rewrite

### ISSUE THREAD

**Issue by L0ric0** [ultrabug/py3status#1542]
As the mpd_status module is quite old and a lot of the parameters have become unnecessary it should be rewritten @lasers has provided a cleaned version at https://github.com/lasers/py3status/tree/newmodule-mpd_status. 

As this will brake old configs I wanted to know if there are features that someone would like to see added.

### New feature proposal:

The possibility to declare multiple hosts and to be able to change them at run time.

At the moment if one wants to have the possibility to display multiple hosts one has to create a whole config for each one and add them to a group. This would work by declaring the host variable as a list and trying to connect to them in order. The {host} placeholder would be overridden by the first server to respond and a button_click event would be defined which would change this to the next host.

**Comment by lasers** [comment]
I'm against built-in multiple hosts because I think it would be not a popular feature and would not be used 99% of the time... And group module already can make this possible... What happen if one of the hosts caught an exception? The whole thing would go down and we would have to wait until next `cache_timeout` or to midde-click on `mpd_status` to get it back.

>and a button_click event would be defined which would change this to the next host.

You should try group config https://github.com/ultrabug/py3status/issues/1537#issuecomment-426819867 to see if it works better. I know the new mpd_status have pause click events without a dedicated pause button... so I wonder if it was the underlying issue here. That and you might not know about `group` button feature. 

Also, group can deal with multiple different music players too... instead of just one.

**Comment by pcewing** [comment]
Is there anything stopping this from being merged? And if so, is there anything I can do to help out? Currently using the implementation in lasers' branch but would be nice to get it in master! :)

**Comment by ultrabug** [comment]
@pcewing AFAIR we never had a formal PR to replace the current one with lasers' one

I'm not sure of the collateral if we did that tho; so maybe you could explain why you like it better and the benefits users would get?

**Comment by pcewing** [comment]
After trying to answer that question, I'm no longer convinced this needs to be
done at all. I was attracted to the simpler configuration settings but a closer
look shows that the following settings are the ones that have been removed:

```
state_pause
state_play
state_stop
max_width
hide_on_error
hide_when_paused
hide_when_stopped
```

While I don't personally use these, I could see how they may be useful so
removing them seems unnecessary.

Sorry for the noise!
