### ISSUE TITLE
Setup error (FileNotFoundError) parse_config.py

### ISSUE THREAD

**Issue by YourDadsHusband** [ultrabug/py3status#1550]
On my installation of py3status on Monjaro linux from the official pacman repository any attempt to launch py3status outside of the command line fails, and when run in the CLI it prints the correct output once, and never refreshes, when running 
py3status -c I3STATUS_CONFIG 
I recieve a File Not Found Error for parse_config.py

**Comment by ultrabug** [comment]
Hi @YourDadsHusband 

Could you copy/paste some complete logs or screenshot to help understanding this? I must admit that I don't get the exact problem with this information for now.

**Comment by lasers** [comment]
Hi @YourDadsHusband @ultrabug

`py3status -c I3STATUS_CONFIG` is not meant to be taken literally.
Replace `I3STATUS_CONFIG` with your config, eg `py3status -c
~/.config/py3status/config` or something like that.

I think `py3status --help` is sometimes confusing. We could print `-c,
--config CONFIG` or `-c, --config FILE` instead of `-c I3STATUS_CONF,
--config I3STATUS_CONF`. Basically, we could clean up `py3status
--help` better. With literal `py3status -c I3STATUS_CONFIG`, we
correctly get `Setup error (FileNotFoundError) parse_config.py`.

>when run in the CLI it prints the correct output once, and never refreshes.

I don't see that happening here. What I think is happening is that
you're on a fresh installation and does not have i3status installed so
py3status is correctly running... just without a config. You can
install i3status and/or to tell py3status where it is.. with `-c`. You
also can put it in correct location for py3status to pick this up.
Unrelated: It looks like py3status does not pick up
`~/.i3/i3status.conf` and `~/.config/py3status/config`.

**Comment by lasers** [comment]
Closed via #1555. I hope everybody find the new help a bit more readable. Thanks.

**Comment by tobes** [comment]
@lasers please be accurate it was fixed via e50bf00eb3c1e7b4603cbbb02d6d06c031245a60 not via #1555 people may want to see the fix
