### ISSUE TITLE
[RFC] version 3.15

### ISSUE THREAD

**Issue by ultrabug** [ultrabug/py3status#1583]
In version 3.15 I would like to propose this:

- use the extended zen from #1582 to close or rework on all open PR for modules
- once merged, black all the modules (and thus all the repository)
- add core support for click events modifiers added in i3 v4.16: https://i3wm.org/docs/i3bar-protocol.html

"That's all", plus any critical bug fix of course.

**Comment by maximbaz** [comment]
\+ Resolution to #1439 🙏 

Don't necessarily want to merge that PR as it is, but I want to be able to click on the module and see a notification with full output of the last execution, without making that module refresh because I just clicked on it. I tried to look into how to make this generic via core, but didn't think of anything good as I described in https://github.com/ultrabug/py3status/issues/1531#issuecomment-437624098.

**Comment by lasers** [comment]
>use the extended zen

I can close many PRs. If I merge `taskwarrior: new module from scratch` and `systemd: new module from scratch`, 3~ issues will be solved, but we will have formatter. Do you want me to go ahead with the easy ones?

>once merged, black all the modules (and thus all the repository)

I can close them instead if needed... because I made them for fun. \o/

>add core support for click events modifiers

I add `py3-cmd --modifer` option. https://github.com/ultrabug/py3status/compare/py3-click-modifiers
* `py3-cmd click --modifier Shift --modifier Mod1 xrandr`

**Comment by ultrabug** [comment]
> use the extended zen from #1582 to close or rework on all open PR for modules

I think that we have applied our Zen very well, we're down to 7 open PRs

> once merged, black all the modules (and thus all the repository)

Done + CI enforced

> add core support for click events modifiers added in i3 v4.16: https://i3wm.org/docs/i3bar-protocol.html

Done by @lasers (thanks)
