### ISSUE TITLE
weather_owm:request timed out

### ISSUE THREAD

**Issue by CuriousFu** [ultrabug/py3status#1722]
weather_owm does not show weather informations ,i click it then it shows "weather_owm:request timed out"

**Comment by ultrabug** [comment]
Hello @CuriousFu 

Unfortunately Yahoo! has discontinued their open weather API since they joined Oath and we have been forced to remove this module from py3status. You can have details in #1612 .

I encourage you to switch to the weather_own module :)

Cheers

**Comment by ultrabug** [comment]
Damn I was too quick and didn't read properly I'm sorry @CuriousFu ...  :laughing: 

Can you try to increase the default (10s) timeout using the `request_timeout` parameter to something higher like 30s or 60s ?

**Comment by lasers** [comment]
@CuriousFu Did you get anywhere with this? We stopped documenting `request_timeout` in modules recently so I don't know what py3status version you're on. Here's an example just in case.
```python
order += "weather_owm"
weather_owm {
    request_timeout = 60
}
```
Additionally, if you had `location` in your config too, then maybe you didn't get anything because the `latitude` and `longitude` are flipped. See issue #1728.

If it's working okay for you now... or it started working again after restarting i3... or you did something else... Either way, please let us know what it was. Don't forget to close this issue too. Cheers.

**Comment by CuriousFu** [comment]
Thank you so much for your kindly and timely help , may you not mind my  not replying you earlier as i changed the "request_timeout" to 60s, the bar shows the "weather_owm" at the first 60s then it shows weather messages normally . How can i make it shown only when it works normally ? Thanks again~

**Comment by lasers** [comment]
@CuriousFu We currently don't have anything to hide errors. You'll have to put up with it. Sorry.
