### ISSUE TITLE
composite frame broken

### ISSUE THREAD

**Issue by ultrabug** [ultrabug/py3status#1736]
0bb3038752203d4ad509b4012c4fac48f12a0e6d broke composite frame separation

try to create a frame module with a module inside, you'll see the separator is not there any more

didn't get the chance to look at why, just reporting

**Comment by lasers** [comment]
Users shouldn't set `markup = pango` inside `frame` because that turns all composites into a single pango markup composite so no separators. We could prevent this for `frame` module with this diff.

I would think that it is not ideal to start deciding what modules can or not do in `module.py`, but this might pose a problem if we wanted `markup = pango` set in py3status configuration section meaning users should have some kind of `<span bg/fg/etc>` in all modules... and do use `frame` somewhere too.

Alternatively, users can set `markup = pango` individually on modules outside of `frame` that will have pango markup in `format` and/or inside the modules that will have pango markup in `format` inside the `frame` to ensure that `frame` module wouldn't be converted to a single pango markup.
```diff
diff --git a/py3status/module.py b/py3status/module.py
index b16ca50..9260d41 100644
--- a/py3status/module.py
+++ b/py3status/module.py
@@ -443,7 +443,8 @@ class Module:
             raise Exception(err)
 
         # set markup
-        if "markup" in self.py3status_module_options:
+        if "markup" in self.py3status_module_options and (
+                self.module_name != "frame"):
             markup = self.py3status_module_options["markup"]
             line = ""
             for item in composite:
```

**Comment by ultrabug** [comment]
Well I do have `markup = "pango"` in my `general` section which I believe is or was the way to go on i3status config so I guess I'll not be the only one in this case

Since it seems to affect only `frame` module, I guess your fix is enough?

**Comment by lasers** [comment]
(Imo) Good enough to prevent `frame`, but not ideal since it's hardcoding `frame` in `module.py` similar to `frameclick`. This prevents/mess with...
```python
order += "frame"
frame {
    format = '<s>FRAME: </s>{output}'
    markup = 'pango'
}
```
The ideal solution (when used with markup)... could be to use `frame`'s fake `format_separator = '|'` (that config lacks `py3.safe_format`).

Better solution is not to blindly using `markup` pango in `general` and in modules where there are no user-defined pango markups in the `format`. 

Small note: It could be good to support `None` too for modules to cancel out `pango`/`none`. I'm not worrying about that right now. You can see the difference between`markup = 'none'` (raw) versus supposedly `None` (unset)... but we have no way to set (or unset) `none`/`pango` option.
