### ISSUE TITLE
on_udev, race conditions and artificial delays

### ISSUE THREAD

**Issue by maximbaz** [ultrabug/py3status#1805]
Sometimes `on_udev` is too quick at refreshing modules, and we need to add an artificial delay.

For example, I noticed that when I add `on_udev_bluetooth` to a `bluetooth` module, the module doesn't get refreshed, but if I add `time.sleep(0.1)` in the beginning of the `def bluetooth(self)`, then everything is perfect.

I imagine such race conditions would not be rare with `on_udev`. What can we do to properly fix this issue? @ultrabug

**Comment by lasers** [comment]
>For example, I noticed that when I add on_udev_bluetooth to a bluetooth module...

Can you share this branch? Thx in advance.

**Comment by maximbaz** [comment]
no new code, it's supported natively, just add this to your config:

    on_udev_bluetooth = "refresh"

**Comment by lasers** [comment]
I'm not sure if there is a race condition, but it might be more about time limit from `bluetooth` data.

Try this without `udev` and activate logging.
```python
order += "bluetooth"
bluetooth {
  cache_timeout = 0.1
}
```
You adding `time.sleep(0.1)` might be a pure coincidence... and ought to be tried more.

`on_udev` seems to be refreshing modules fine and that `bluetooth` could came back with nothing. If you refresh `i3` few seconds after activating a bluetooth device, then it may behave just same as your `time.sleep(0.1)`.

With logging, it shows that activating a device fires off a name for about 3 seconds before it stops. For the record, I tried this with keyboard. Mouse may be a bit more active with BT popping in and out on udev. With `cache_timeout = 10`, it could give users more leeway since users are likely to keep using BT keyboard and/or mouse.

Possible solution: Implement a minimal timeout for displaying device names before stopping... which ought to be longer than 3 seconds.

Anyhow, that's what I think. See if it is same for you.

**Comment by lasers** [comment]
My finding still stands, but I think you're looking for this. Wait `0.1` (?) to allow processing.  
```diff
diff --git a/py3status/udev_monitor.py b/py3status/udev_monitor.py
index 97f205f..e685121 100644
--- a/py3status/udev_monitor.py
+++ b/py3status/udev_monitor.py
@@ -1,5 +1,6 @@
 from collections import defaultdict
 
+from time import sleep
 from py3status.constants import ON_TRIGGER_ACTIONS
 
 try:
@@ -81,4 +82,5 @@ class UdevMonitor:
                     "%s udev event, refresh consumer %s"
                     % (subsystem, py3_module.module_full_name)
                 )
+                sleep(0.1)
                 py3_module.force_update()

```

**Comment by maximbaz** [comment]
> on_udev seems to be refreshing modules fine and that bluetooth could came back with nothing. If you refresh i3 few seconds after activating a bluetooth device, then it may behave just same as your time.sleep(0.1).

Sorry for a slow response, travelling this week :) Yes this is exactly what happens, `on_udev` is refreshing as expected, but modules themselves might be slow to notice the change; in case of bluetooth, even though udev has already seen a new bluetooth device, the dbus library that bluetooth module is using still reports "no devices".

For this reason, I don't think a hardcoded `sleep(0.1)` is a good enough solution, other modules might be even slower and require a longer delay; perhaps an additional optional config of `on_udev_delay = N` or `on_udev_XXX_delay = N` could be introduced, which defaults to `0` or `0.1` depending on your taste?

**Comment by lasers** [comment]
Although hardcoded, `sleep(0.1)` might be enough and does not require a drastic change. I assume `battery_level` and `xrandr` would manage okay with this delay too.

Alternatively, could make https://github.com/ultrabug/py3status/issues/1531#issuecomment-474627091 for `on_udev` too.

```python
# default
bluetooth {
    on_udev = [
        {
          "subsystem": "bluetooth",
          "action": "refresh",
          "delay": 0.1,
        }
    ]
}
```
```python
# default
battery_level {
    on_udev = [
        {
          "subsystem": "power",
          "action": "refresh",
        }
    ]
}
```
Can ask @ultrabug for an input too. Your `on_udev_xxx_delay = N` should be fine, but could create a really trivial new config for modules that uses udev (either with or without delay). I haz no preference.

**Comment by maximbaz** [comment]
given that I don't know real examples where a larger delay is needed, we could very well start from hard coding sleep(0.1), and once we learn where it's not enough, we replace sleep with something smarter, I'd be okay with that too I guess. Let's hear @ultrabug 😉

**Comment by ultrabug** [comment]
I think that 100ms is not noticeable for a human being, so I would keep it simple and go for it until someone else has a stronger opinion.

I'll go ahead and add it myself.

Thanks!
