### ISSUE TITLE
A placeholder to move some modules to the left - a "spacer" module? 

### ISSUE THREAD

**Issue by nwg-piotr** [ultrabug/py3status#1841]
I searched the docs quite carefully, and still have no idea on how to move one or more modules to the left side of the panel. For instance I'd like to move the first module here:

![screenshot_2019-09-20_01-01-45_203059729](https://user-images.githubusercontent.com/20579136/65287290-eeaab480-db42-11e9-8196-16451bcb226b.png)
 for it to look something like this:

![qtile-bottom-panel](https://user-images.githubusercontent.com/20579136/65287304-fe29fd80-db42-11e9-8b09-4a0703720938.png)

Lately I found out that qtile comes with a module called "spacer", which does the job. Would it be possible in py3status?

**Comment by lasers** [comment]
Duplicate #1370. py3status sends stuff to i3bar.

**Comment by nwg-piotr** [comment]
Well, not really [what I'm thinking about](https://github.com/qtile/qtile/blob/master/libqtile/widget/spacer.py), but OK. Probably it wouldn't be easy to know the current total length of all widgets to calculate the spacer. :/

**Comment by lasers** [comment]
>Probably it wouldn't be easy to know the current total length of all widgets to calculate the spacer.

(Exaggeration) That one might not be too hard. I think the issue is that spacer could be used only once to place it in either left or center, but no spaces between modules.

Also, py3status or others can't determine length of workspace numbers and/or names on left side so some modules can be hidden if users have too much workspaces (and we would never be able to adjust them accordingly).

Maybe spacer module could be used more than once (i.e. left and center) because it would be part of current total length of widgets and we would have to, I dunno, parse the config too (or just use its parsed_config dict instead) to determine which modules to use/calculate.

We don't have anything like this and does not sound easy. :D

**Comment by lasers** [comment]
I started and stopped. Put it at end of the `order` list and adjust the width to get left or center. Container modules excluded. https://github.com/lasers/py3status/tree/newmodule-spacer

**Comment by nwg-piotr** [comment]
The problem is that some of modules (including some external scripts, which are mine), have no fixed width. So the spacer width (length) would have be recalculated. 

If it comes to workspaces, I only display them in the top bar of the primary display, and I use [my script](https://github.com/nwg-piotr/swayinfo/blob/master/wsdnames-i3ipc-2.0.1.py) to rename them dynamically.

For now I added one more sway-bar, which is an overlay over the bottom bar on the primary display. It looks not bad, but it's just a not clickable workaround.  

![screenshot_2019-09-21_14-46-06_423261553](https://user-images.githubusercontent.com/20579136/65373555-549c5680-dc7f-11e9-83eb-dd59dd1b41b3.png)

I'll take a closer look at the new branch in the evening. I may need much more coffee. ;) Thanks for time taking to resolve my little issue.

**Comment by nwg-piotr** [comment]
Alright - the spacer module seems to work well enough. If the last module output only (before the spacer) changes its length, all the content does not float, so I added leading zeros to my UL/DL script. This resolves the problem. Thank you once again!

![screenshot_2019-09-21_23-11-22_255541444](https://user-images.githubusercontent.com/20579136/65379237-30fbff00-dcc5-11e9-950e-f33dca1909ee.png)
