### ISSUE TITLE
[Module Enhance] Arch Updates

### ISSUE THREAD

**Issue by mlmatlock** [ultrabug/py3status#1887]
I don't use AUR 'helpers', and I use a custom repository (defined in pacman.conf), along with Alad's [aurutils](https://aur.archlinux.org/packages/aurutils/) to manage it.  This results in no foreign `(pacman -Qm)` packages installed; which negates `auracle sync`.

Can the command `aur sync -u` be added to the module to get this functionality?

Sample output (no updates at this time):

` aur sync -u`
>==> Using [custom] repository
>   there is nothing to do

**Comment by maximbaz** [comment]
At this stage I think it's something you should manage via `external_script` functionality. You can get number of pending updates via `aur repo -u` (`sync` actually downloads and builds new versions of packages), but this still won't give you numbers for outdated vcs packages (e.g. those that end with `-git`) - for that you need to create your own script like `aur vercmp-devel` following the example in manual - and since there is no standard interface for this, anything you put in `py3status` would be very specific to your own setup. 

Here is an example from my own setup, if you seek some inspiration:  

https://github.com/maximbaz/dotfiles/blob/master/.config/py3status/config#L101

There was once proposed an idea to redesign and rewrite py3status module for package updates, but that didn't happen as of today.

**Comment by mlmatlock** [comment]
Thanks for the hint and clarification, Maxim!

**Comment by ultrabug** [comment]
Closing then, thanks
