### ISSUE TITLE
Depends on 'which'

### ISSUE THREAD

**Issue by JasonPPS** [ultrabug/py3status#1994]
On a basic arch-linux install with i3-gaps, py3status is unable to launch. I fixed this by installing the [which](https://archlinux.org/packages/core/x86_64/which/) package that is included in the [base-devel](https://archlinux.org/groups/x86_64/base-devel/) group. Perhaps this needs to be included in the dependencies. 

See output in the [pastebin](https://pastebin.com/2NTNs7zB) when 'which' is uninstalled.

**Comment by ultrabug** [comment]
Thanks for reporting this @JasonPPS 

This is actually a packaging issue since it's distribution specific

Friendly ping @maximbaz

**Comment by diabonas** [comment]
I added a dependency on `which` in [py3status 3.31-3](https://github.com/archlinux/svntogit-community/commit/e7856c9dfdb3cb87d120392d96d7ef86e344e892). However, I'd  muchprefer it if py3status could just use [`shutil.which`](https://docs.python.org/3/library/shutil.html#shutil.which) (added in Python 3.3) instead of relying on external utilities. Is there anything speaking against that, @ultrabug? I'm happy to provide a pull request.

**Comment by ultrabug** [comment]
Thank you!
