### ISSUE TITLE
[weather-owm] Rainfall not displayed

### ISSUE THREAD

**Issue by mlmatlock** [ultrabug/py3status#2032]
**Describe the bug**

Even with 'format_rain' set, output dows not display rainfall.

**Your py3status version**

py3status version 3.35 (python 3.9.2) on sway (Arch Linux)

**To Reproduce**
Steps to reproduce the behavior along with your py3status configuration (filter out any private values):
1. Add module '...'

order += "weather_owm"

2. Configure module like this '....'
```
weather_owm {
		color = '#8ABEB7'
		gradients = 'true'
                api_key = redacted
		city = 'Robins Air Force Base'
		thresholds = {
            'current': [
            (40, "cold"),
            (50, "chilly"),
            (65, "nice"),
            (85, "hot")
            ], 
            'humidity': [
	                (30, "good"),
                        (50, "degraded"),
                        (75, "bad")
			]
		}
		format_temperature = '[\?color=current {current:.0f}°{unit}]'
        format_pressure = '{pressure:.1f} mb'
		format_humidity = '[\?color=humidity {humidity}%]'
		format_wind = '[\?if=speed {degree:.0f}° {speed:.0f} {unit}  G:{gust:.0f} {unit}]'
        format_rain = '[\?if=amount {amount:.0f} in {unit}]'
		format = 'KWRB  {wind}   {description}   {temperature}  {humidity}  {pressure}  [ {rain}]  {forecast} '
        on_click 1 = "exec qutebrowser https://bit.ly/2HwjCbC"
		on_click 2 = "exec qutebrowser https://radar.weather.gov/?settings=v1_eyJhZ2VuZGEiOnsiaWQiOiJ3ZWF0aGVyIiwiY2VudGVyIjpbLTgzLjY3OSwzMi41NzFdLCJ6b29tIjo3LCJsb2NhdGlvbiI6Wy04My42NzksMzIuNTcxXX0sImJhc2UiOiJzdGFuZGFyZCIsImNvdW50eSI6ZmFsc2UsImN3YSI6ZmFsc2UsInN0YXRlIjpmYWxzZSwibWVudSI6dHJ1ZSwic2hvcnRGdXNlZE9ubHkiOmZhbHNlfQ%3D%3D#/"
		on_click 3 = "exec qutebrowser https://tgftp.nws.noaa.gov/weather/current/KWRB.html"
}
```
3. Run py3status '....'

See screenshot.

![20210331_19h38m43s_grim](https://user-images.githubusercontent.com/42914546/113224770-21fef100-925a-11eb-9031-c9af271e8f92.png)

No rain, even with the conditional '[ {rain}]' set to '{rain}'

**Expected behavior**

Should have rainfall.

**Additional context**

This is the output of manually querying openweathermap from qutebrowser:
```
{"coord":{"lon":-83.5844,"lat":32.6091},"weather":[{"id":501,"main":"Rain","description":"moderate rain","icon":"10d"}],"base":"stations","main":{"temp":291.15,"feels_like":291.62,"temp_min":291.15,"temp_max":291.15,"pressure":1017,"humidity":100},"visibility":10000,"wind":{"speed":1.54,"deg":130},"rain":{"1h":2.73},"clouds":{"all":90},"dt":1617232500,"sys":{"type":1,"id":6264,"country":"US","sunrise":1617189792,"sunset":1617234798},"timezone":-14400,"id":7260641,"name":"Robins Air Force Base","cod":200}
```
Notice the rain output above, with the "1h".

**Comment by lasers** [comment]
Fix your code formatting by adding triple backticks ` ``` ` before and after the code. I can try and look at this.

**Comment by lasers** [comment]
From what I think...

This code don't care about `1h` in the dict you showed, but gets its data from different endpoint.

There, it uses `3h` from forecast url (below). The `format_rain` mentioned over the past 3 hours too. https://github.com/ultrabug/py3status/blob/1107fd19be8d45d11aeb7f1c61eecd9c0b4ee323/py3status/modules/weather_owm.py#L281 

```shell
# Replace xxx with your api_key.
https://api.openweathermap.org/data/2.5/weather?appid=xxx&q=02108
https://api.openweathermap.org/data/2.5/forecast?appid=xxx&q=02108
```

Then any rainfalls that are at `0.5` or below will be rounded down. Some are in mm, some are in inches. You wanted inches, so that's `3h_rain * 0.0393701` being rounded down to `0` inches. At `0.51` or above, you would get `1` inches. https://github.com/ultrabug/py3status/blob/1107fd19be8d45d11aeb7f1c61eecd9c0b4ee323/py3status/modules/weather_owm.py#L558-L565

Imho, this shouldn't be hardcoded in first place, but even if it wasn't, the default `format_rain` would be rounding down/up this amount too because of rounded `{amount:.0f}` instead of precise `{amount}`. 
https://github.com/ultrabug/py3status/blob/1107fd19be8d45d11aeb7f1c61eecd9c0b4ee323/py3status/modules/weather_owm.py#L326

With `0` inches, you get no rainfall. :cry: 

P.S.

>No rain, even with the conditional '[ {rain}]' set to '{rain}'

Because of `format_rain = '[\?if=amount {amount:.0f} in {unit}]'` where `amount` got `0` so it doesn't show anything. If you add `format_rain = '{amount} {unit}'` or `format_rain = '{amount}'`, you should see something.

I hope that clears things up. PRs welcome. :+1:

**Comment by mlmatlock** [comment]
@lasers-Ok, I understand how the conditional (with the rounding) works now.

I changed my formatting line to ```format_rain = '{amount} {unit}'```, and something different came up.

No rain here for 12 hours, so amount=0.  So, shouldn't the ```[ {rain}]``` in the ```format``` string be a match, and rain *not* displayed (it is)?

**Comment by lasers** [comment]
Thoughts.
1) According to openweathermap.org, it may be better to use `1h` to better reflect current amounts for rain + snow.
2) Static weather units = Stoopid? It looks like options like `ft`, `yd`, is practically nonexistent because of two reasons... rounding and this is for no more than current `1h|3h` rain + snow.

3) Places that doesn't have rain + snow data will give users false value `0`. Nonexistent / `None` is more clear.
4) Your `1h` --> `2.73 mm`... converting to... `0.1074803 in`... rounding to `0 in`.
   Your `3h` is likely to be less than `1h` so currently, you are likely to always get `0 in` than `1 in`.

5) Change default units to `mm` to make rain + snow placeholders appear more often.
5) Change default rounding to `:.2f` to make rain + snow placeholders appear more often.

>No rain here for 12 hours, so amount=0. So, shouldn't the [ {rain}] in the format string be a match, and rain not displayed (it is)?

Default `format_rain` config is set up like `if amount is not zero, show this block`. With just `format_rain = '{amount} {unit}'`, `{rain}` will show `0 inches`. If we get rid of rounding and change default units to `mm`, then you would see it more often.

I can get rid of rounding tonight.
