### ISSUE TITLE
fedora updates shows questionmark

### ISSUE THREAD

**Issue by Bysmyyr** [ultrabug/py3status#2105]
**Describe the bug**
Fedora updates show only question mark. It worked in my previous laptop but not with this

**Your py3status version**
➜ py3status --version
py3status version 3.34 (python 3.10.2) on i3
➜ cat /etc/fedora-release
Fedora release 35 (Thirty Five)

**To Reproduce**
add fedora_updates:
```
order += "fedora_updates"
fedora_updates{}
```

**Expected behavior**
see number

**Comment by lasers** [comment]
I glanced at the module. `DNF: ?` will always occur on first loop, then you should get your number.

Try running `dnf check-update`. All good? You can try running `dnf updateinfo` too. See if it's giving you an issue.

Maybe this module need to be updated. Maybe not. Idk. You have `check_security` config too. Just play around and see if anything turns up. You might have to wait a while too as I remember this can take some time... hence the first `DNF: ?`.

**Comment by Bysmyyr** [comment]
```➜ dnf updateinfo
Waiting for process with pid 2368 to finish.
```


```➜ dnf updateinfo
Waiting for process with pid 2368 to finish.
^CKeyboardInterrupt: Terminated.
```

```➜ ps -aux | grep 2368
olli        2368  0.0  0.2 378816 70176 ?        S    Mar13   0:00 /usr/bin/python3 /bin/dnf check-update
```

All command work with sudo.

What is check_security config?

**Comment by lasers** [comment]
>^CKeyboardInterrupt: Terminated.

Did it finish? If it takes that long in the terminal, then it should take that long in py3status module too. Also, if it outputs packages or such in the terminal, share here. I could try and test this module against the output.

>check_security = True

If this is `True`, then it may execute a different `dnf` command thus it could need more time.

Basically, the issue is that the module is waiting for an output from `dnf`... Waiting as long as it can.

Also, it looks like it's waiting for process with pid 2368 to finish first. You or the system could have been running `dnf` somewhere else so it's just waiting for that process to finish first.

No `sudo` in this module too.

**Comment by lasers** [comment]
Worked fine here with Fedora i3 iso (thirty six beta prerelease).  I get `DNF: 470` on the bar.

`dnf update` printed `10` to-be-installed and `304` to-be-upgraded.

The module is displaying a number either way.

After updating, I get `DNF: 0`. I think it is an issue with dnf on on your side.
