### ISSUE TITLE
'Clock' module only shows '?' now.

### ISSUE THREAD

**Issue by macxcool** [ultrabug/py3status#2188]
**Describe the bug**
The 'clock' module only shows a question mark '?' no matter what I try. This has only happened in the last couple of days?

**Your py3status version**
py3status version 3.50 (python 3.11.3) on i3

**To Reproduce**

1. Add module 'clock' to i3status config file
2. It doesn't seem to matter how I configure the module. I haven't changed the config for years
3. Run py3status
4. The section of the i3bar where the clock module should be shows '?'

**Expected behavior**
The clock and time should show like normal.

**Additional context**
I'm running Archlinux and everything is up-to-date. Everything else in my py3status config seems to be working fine. I have the 'clock' stuff inside a 'frame' along with some other elements.

**Comment by schmijoe** [comment]
This seems to be caused by 

https://github.com/ultrabug/py3status/blob/d27bb8565acdd394a24d170cf99118eedbced8e0/py3status/modules/clock.py#L191-L195

as `ZoneInfo` seems to (no longer?) support "localtime".

As a temporary fix you can specify your timezone directly in the config file:


```
clock {
  format="{Europe/London}"
}
```

**Comment by macxcool** [comment]
Perfect. That works for now. Thanks!

**Comment by sixy6e** [comment]
Specifying the timezone certainly works, but not having to specify would be better, especially for when travelling.  I could get around it by changing the config to use the `tztime` module (from i3bar I believe) instead of `clock`.

I installed `tzdata` from pip, but it didn't do anything, and if `ZoneInfo` no longer supports "localtime" as an input, an alternative is to return `None` as the Python docs imply that `datetime.datetime.now(None)` returns local time. eg:

```python
if tz == "Local":
    return None
```

As no `ZoneInfo` class is returned, None needs to be explicitly handled at:

https://github.com/ultrabug/py3status/blob/master/py3status/modules/clock.py#L254-L255

eg

```python
if zone is None:
    timezone = None
    tzname = None
else:
    timezone = zone.key
    tzname = timezone.split("/")[-1].replace("_", " ")
```

Not very pretty in explicitly handling `None`, and no idea of widespread impacts (it seems to work for me at the moment), but I'd be happy to submit a PR if the idea is suitable for the maintainers.

**Comment by lasers** [comment]
>I'd be happy to submit a PR if the idea is suitable for the maintainers.

Go for it. Easier to review your code.

**Comment by ultrabug** [comment]
Thanks for your PR
