### ISSUE TITLE
modules : normalize & document cache_timeout

### ISSUE THREAD

**Issue by ultrabug** [ultrabug/py3status#417]
Normalize the use of `self.py3.time_in()` in all modules.

**Comment by tobes** [comment]
I also want to update `time_in()`

* add a `sync` option so that the time can be synced to the x second eg `time_in(10, sync=60)` would get the next minute after 10 seconds, useful for clocks/timers etc (`sync` is a horrible name need to think of a better one)

* add an `offset`  option so that the base time can be different again useful for timers

**Comment by tobes** [comment]
I was thinking about this some more.

First I thought we should change `time_in(seconds)` so that if we don't supply a time then we use the value in the modules `cache_timeout` so we can just use `self.py3.time_in()` instead of `self.py3.time_in(self.cache_timeout)`.  This would change the behavior slightly when we call `time_in()` (currently this requests an immediate update), but as we have few users at present, now would be the ideal time to do it.

Then I thought why even be this explicit?  If a module methods response does not include `cached_until` then we could just assume that we should use the modules `cache_timeout`, currently we use the value from `py3status --timeout x` so it would be a small change and unlikely to break anything.  we would still use that as the default if a module has no `cache_timeout`.  This has the side effect of allowing the user to set `cache_timeout` for modules that do not currently have it as a parameter.

I think that we should adopt both these ideas.  Also, if we are going to switch modules to use `safe_format()` that it would be a good opportunity to make both changes at the same time (though maybe as separate PRs).

I also think we should sneak this into 3.1

**Comment by pydsigner** [comment]
I really like this `cache_timeout` idea. +1 for that.

**Comment by ultrabug** [comment]
I'm up for all those proposals, they make perfect sense to me. The implicit usage and its fallback should be documented tho.

Cheers !

**Comment by tobes** [comment]
Added as #422

**Comment by tobes** [comment]
Implemented in #422 & #429 
Documentation of the automatic setting of 'cached_until' wants improving
