### ISSUE TITLE
config values not available on init

### ISSUE THREAD

**Issue by tablet-mode** [ultrabug/py3status#50]
Sorry for noticing this only now, but it appears that in the init function of the Py3status class the values from i3status.conf are not available yet. So when you want to set up some things, just when the module is loaded for the first time, you won't be able to use the config values.

**Comment by ultrabug** [comment]
Yes indeed @tablet-mode but we can't do anything about this since __init__() is always called automatically upon instantiation.

I had to handle this kind of behavior when I updated all modules so you can have a look at how it can be done in the net_rate module for example : https://github.com/ultrabug/py3status/blob/master/py3status/modules/net_rate.py

Nothing prevents you also from calling a special _setup() method also to do it more cleanly.

**Comment by tablet-mode** [comment]
I was afraid of that. I actually already have a workaround for it, I just wanted to make sure :-)

Thanks anyway.
