### ISSUE TITLE
twitch_streaming: stream_name does not exist 

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#613]
I'm unable to set up `twitch_streaming`. This module does not work at all.
I kept getting `{whatever_the_name_is} does not exist!`

Old module? Also, it might had something to do with this? 
https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843

EDIT:  Is `cache_timeout = 10` not too aggressive for default cache_timeout?

**Comment by tobes** [comment]
I think you might be right,  This isn't a module that I use.  I think you may be right about the api key  I'm not sure if we can get a clientID for py3status (which would just be in plaintext in the module) or if each user would need to get there own.

**Comment by lasers** [comment]
@tobes Thoughts on removing this module before the version bump? It's past the expiration date. Here's the possible options for the future.

* A: **twitchy** *(CLI livestreamer / streamlink wrapper for twitch.tv)* https://github.com/BasioMeusPuga/twitchy is something py3status should be able to parse output from...

* B: **twitch.py** *(New module)* Somebody write a new module with data coming from https://twitch.tv + `client_id/api_key` and expose everything as placeholders. Likely an excellent choice.

**Comment by tobes** [comment]
My preference would be to get the existing module to work again rather than replacing it.

The problem is the user is going to need to get a client_id etc.  I'm not sure why they've decided to do this but it sure stops me using their api.  If you can get it to work without the client_id stuff then great but I'm not sure how easy it is.

Really like all modules this needs someone who cares about them.  The other option is just to kill it

**Comment by lasers** [comment]
I care. https://github.com/lasers/py3status/tree/newmodule-twitchy

**Comment by tobes** [comment]
twitchy looks like it is using a client_ID limited to 30 requests/min

**Comment by lasers** [comment]
Fixed via #1295.
