### ISSUE TITLE
Setting order in which methods are called from Py3status class

### ISSUE THREAD

**Issue by shankargopal** [ultrabug/py3status#64]
First off, thank you for this wonderful program and all the work you've done on it.

I had a question.  Py3status calls all the methods in the class Py3status in any script we write in the concerned directory.  I'd like to control the order in which the output of the the methods from within one module are displayed.  There is a way to control the order in which the output from a module is displayed (using "order+=" etc. in the config).  Is there any way to control the order in which the output from each method within that module is displayed?

**Comment by ultrabug** [comment]
hi @shankargopal, glad you like py3status :)

The `order +=` controls only how modules are displayed between them, not how to order a module's multiple output.

But there's a way to do what you need here because module's methods are sorted alphabetically when they get loaded. So you should be able to order them by simply ordering them by their name ;)

Hope this helps.

**Comment by shankargopal** [comment]
Thanks ultrabug for the quick reply.

But that doesn't seem to work, for some reason that I'm not able to understand.  I use a slightly unorthodox method of defining a class, and then adding methods to that class dynamically (because I want the output to contain different colors, and it seems that the output from a single method can have only one color).  The relevant bit of the code looks like this:

     class Py3status:
          pass

     alphabets = "abcdefghijklmnopqrstuvwxyz"
     for daycount in range(0,totaldays + 1):
           methname = "_check"
           setattr(Py3status, alphabets[daycount] + methname, make_cal_func(daycount))

where make_cal_func returns a lambda function that in turn returns the correct dictionary.  The output of each method is being produced correctly and in the correct color.  As far as I can understand it, the method corresponding to `daycount` being 0 - which is called a_check - should be called first and its output should appear leftmost.  In practice that doesn't happen.  I have three days' worth of events right now and b_check is being displayed first, then a_check, then c_check.  Any idea what is going on?

**Comment by ultrabug** [comment]
Hi mate,

First, I think you approach is fun and neat, congratz ! I never imagined such a use case :)

I indeed made a mistake in my first answer, methods are sorted when they are **loaded** in a dict but they are not sorted when py3status **iterates** on the dict to get their output. Since dicts do not preserve ordering that explains your problem.

I'll propose a fix in a branch asap mate, shouldn't be too hard. I'll keep you posted here.

**Comment by shankargopal** [comment]
Thanks, it was an experiment for me too :).  I'm sorry I can't
contribute a patch.  Thanks again for such
a neat tool :)

**Comment by ultrabug** [comment]
Hi @shankargopal, I've commited on the `issue64` branch a fix for this issue which ensures that methods are sorted alphabetically.

Please have a look and give me your feedback, I'll merge it to master.

**Comment by shankargopal** [comment]
A great change, I was also thinking that that would be the easiest way
to do it.  I incorporated the change into the script on my system - I'm
not very familiar with git on remote repositories (only used it
locally) so didn't try a clone, just added it in manually.  It seems to
be working beautifully.  Thanks a lot, as always!

**Comment by ultrabug** [comment]
Cool, thank you too mate, it's merged into master.
