### ISSUE TITLE
Not working colors

### ISSUE THREAD

**Issue by suuuehgi** [ultrabug/py3status#926]
Hey,

are the format tags on the wiki right? E.g. [sysdata](http://py3status.readthedocs.io/en/latest/modules.html#sysdata):

> (default ‘[?color=cpu CPU: {cpu_usage}%], ‘ ‘[?color=mem Mem: {mem_used}/{mem_total} GB ({mem_used_percent}%)]’)

I don't get the colors to work. As soon as I set the format-tag everything is white. The above citation evaluates to e.g. `‘?color=cpu CPU: 2.33%,‘...`

In terms of color, I solely have set:
 ```
general {
    color_good = '#00AA00'
    color_bad = '#FF0000'
    color_degraded = '#F4D871'
    color_charging = '#4EC0FF'
}
```

Thanks alot!

**Comment by lasers** [comment]
Hi there.
>are the format tags on the wiki right? E.g. sysdata:

The format is wrong in the `readthedocs`. Good catch. 👍

Docs are pulled from the docs sitting inside the modules.
* Module doc: [sysdata.py#L7-L9](https://github.com/ultrabug/py3status/blob/master/py3status/modules/sysdata.py#L7-L9)
* Actual code: [sysdata.py#L213-L214](https://github.com/ultrabug/py3status/blob/master/py3status/modules/sysdata.py#L213-L214)

Try this...
```
format = "[\?color=cpu CPU: {cpu_usage}%], [\?color=mem Mem: {mem_used}/{mem_total} GB ({mem_used_percent}%)]"
```
Use `format +=` if you want to break up long line.
```
format = "[\?color=cpu CPU: {cpu_usage}%], "
format += "[\?color=mem Mem: {mem_used}/{mem_total} GB ({mem_used_percent}%)]"
```
Thanks for this.

**Comment by smoneck** [comment]
Thanks a lot! Ya, the slash is being parsed out... Could have thought it but it was 6 in the morning... :)

**Comment by smoneck** [comment]
P.s.: How about adding the default config of `format` to the wiki? I'm currently wondering about the color attributes/tags apart from `sysdata`.

**Comment by lasers** [comment]
>P.s.: How about adding the default config of format to the wiki?

CC @tobes 

>I'm currently wondering about the color attributes/tags apart from `sysdata`.

AFAIK There are no formatter documentation yet. I'll give it a try.

You can replace `COLOR` in... `[\?color=COLOR]` with... 
* bad          // tied to `color_bad`
* good        // tied to `color_good`
* degraded // tied to `color_degraded`
* #ffccff // custom (full)
* #fcf // custom (short)
* ----- // color names that may or may not be added in the future... like `orange`, `silver`, `lime`, etc.

I see that `sysdata` uses only one `thresholds` number to colorize all parameters so that might be hard to configure because numbers could be clashing with each others.

You may have to use `[\?color=COLOR&show Hello]` sometimes only if there are no parameter to work with. There are more to it than just `colors`. We got `if`, max_length, `has_zero`, etc... More formatter options could be implemented eventually in the future. @tobes recently added `soft` not long ago to deal with empty parameters, eg `{artist}[\?soft - ]{title}` becomes `Loud Radio` instead of `- Loud Radio`.

See [test_formatter.py](https://github.com/ultrabug/py3status/blob/master/tests/test_formatter.py) for some good examples.

You may know about `color_{good, bad, degrade}`, but not `color = #ffccff`. That option should colorize the particular module pink... only if it's not being colorized by other `color_` options.

Anyhow, I hope that helps things.

**Comment by smoneck** [comment]
Thank you very much for all the effort! I'll play around with the attributes and see what I can do. :-)

Just one thing: `test_formatter.py` gives me:
```
Expected
'something'
Got
''
Traceback (most recent call last):
  File "test_formatter.py", line 1133, in <module>
    getattr(this_module, name)()
  File "test_formatter.py", line 1106, in test_module_true
    'expected': 'something',
  File "test_formatter.py", line 112, in run_formatter
    assert (result == expected)
AssertionError
```

**Comment by lasers** [comment]
As for that `test_formatter.py`, you have to wait for somebody else. Quick glance... it looks like you failed one of the tests... (Test No 148 `test_module_true` on `Line 1103`) out of 152 tests (assuming you didn't change anything). I'm unfamiliar in that area of `py3status`... only modules. 

Just in case, what distro are you using? And py3status version? `py3status -v`?  

P.S. I can run `format = 'L1: {load1} // L5: {load5} // L15: {load15}'` okay here.
Maybe it's an outdated version issue... or a typo or something on your side?

**Comment by smoneck** [comment]
Yes, you were right! I had `py3status version 3.5 (python 3.6.1)` running, what is the current version in AUR. With `py3status-git` (`py3status version 3.6rc1`) it's working. Now `test_formatter.py` runs without errors as well but with zero output. Should this be the case?

**Comment by lasers** [comment]
`py3status-git` --> `py3status version 3.6rc1 (python 3.6.1)`. All okay.

>Now test_formatter.py runs without errors as well but with zero output. Should this be the case?

Yes, I believe so. Nothing is wrong... Nothing to report. You're meant to look at them to get some ideas on how currently available formatters works... along with good examples. No need to run them.

Things sounds okay now. You can leave this issue open until somebody tweaks things inside `readthedocs` to not eat the slashes inside the docs. If you got more questions, I can try and answer them. Cheers.

**Comment by smoneck** [comment]
Thanks a lot! :-)

**Comment by maximbaz** [comment]
Related to this issue, modules `net_rate` and `disk_data` define default `thresholds` with colors, but their default `format` values don't have `[\?colorXXX` markers. This was very confusing to me, I spent quite some time now investigating why I define thresholds but colors don't change 🙂

**Comment by tobes** [comment]
I'm closing this @maximbaz with your issue above make a new issue if it is still relevant
